#!/bin/sh
Rscript simulate_and_test.R UniformStrip 0.3 truncation "c()" sim/prms.sim.1.Rdata > out/run.sim.s.1.rho.0.3.out  &
Rscript simulate_and_test.R Gaussian -0.9 truncation "c()" sim/prms.sim.2.Rdata > out/run.sim.s.2.rho.-0.9.out  &
Rscript simulate_and_test.R Gaussian -0.8 truncation "c()" sim/prms.sim.2.Rdata > out/run.sim.s.2.rho.-0.8.out  &
Rscript simulate_and_test.R Gaussian -0.7 truncation "c()" sim/prms.sim.2.Rdata > out/run.sim.s.2.rho.-0.7.out  &
Rscript simulate_and_test.R Gaussian -0.6 truncation "c()" sim/prms.sim.2.Rdata > out/run.sim.s.2.rho.-0.6.out  &
Rscript simulate_and_test.R Gaussian -0.5 truncation "c()" sim/prms.sim.2.Rdata > out/run.sim.s.2.rho.-0.5.out  &
Rscript simulate_and_test.R Gaussian -0.4 truncation "c()" sim/prms.sim.2.Rdata > out/run.sim.s.2.rho.-0.4.out  &
Rscript simulate_and_test.R Gaussian -0.3 truncation "c()" sim/prms.sim.2.Rdata > out/run.sim.s.2.rho.-0.3.out  &
Rscript simulate_and_test.R Gaussian -0.2 truncation "c()" sim/prms.sim.2.Rdata > out/run.sim.s.2.rho.-0.2.out  &
Rscript simulate_and_test.R Gaussian -0.1 truncation "c()" sim/prms.sim.2.Rdata > out/run.sim.s.2.rho.-0.1.out  &
Rscript simulate_and_test.R Gaussian 0 truncation "c()" sim/prms.sim.2.Rdata > out/run.sim.s.2.rho.0.out  &
Rscript simulate_and_test.R Gaussian 0.1 truncation "c()" sim/prms.sim.2.Rdata > out/run.sim.s.2.rho.0.1.out  &
Rscript simulate_and_test.R Gaussian 0.2 truncation "c()" sim/prms.sim.2.Rdata > out/run.sim.s.2.rho.0.2.out  &
Rscript simulate_and_test.R Gaussian 0.3 truncation "c()" sim/prms.sim.2.Rdata > out/run.sim.s.2.rho.0.3.out  &
Rscript simulate_and_test.R Gaussian 0.4 truncation "c()" sim/prms.sim.2.Rdata > out/run.sim.s.2.rho.0.4.out  &
Rscript simulate_and_test.R Gaussian 0.5 truncation "c()" sim/prms.sim.2.Rdata > out/run.sim.s.2.rho.0.5.out  &
Rscript simulate_and_test.R Gaussian 0.6 truncation "c()" sim/prms.sim.2.Rdata > out/run.sim.s.2.rho.0.6.out  &
Rscript simulate_and_test.R Gaussian 0.7 truncation "c()" sim/prms.sim.2.Rdata > out/run.sim.s.2.rho.0.7.out  &
Rscript simulate_and_test.R Gaussian 0.8 truncation "c()" sim/prms.sim.2.Rdata > out/run.sim.s.2.rho.0.8.out  &
Rscript simulate_and_test.R Gaussian 0.9 truncation "c()" sim/prms.sim.2.Rdata > out/run.sim.s.2.rho.0.9.out  &
Rscript simulate_and_test.R Clayton 0.5 truncation "c()" sim/prms.sim.3.Rdata > out/run.sim.s.3.rho.0.5.out  &
Rscript simulate_and_test.R Gumbel 1.6 truncation "c()" sim/prms.sim.4.Rdata > out/run.sim.s.4.rho.1.6.out  &
Rscript simulate_and_test.R LD 0 truncation "c()" sim/prms.sim.5.Rdata > out/run.sim.s.5.rho.0.out  &
Rscript simulate_and_test.R LD 0.4 truncation "c()" sim/prms.sim.5.Rdata > out/run.sim.s.5.rho.0.4.out  &
Rscript simulate_and_test.R nonmonotone_nonexchangeable -0.9 truncation "c()" sim/prms.sim.6.Rdata > out/run.sim.s.6.rho.-0.9.out  &
Rscript simulate_and_test.R nonmonotone_nonexchangeable -0.8 truncation "c()" sim/prms.sim.6.Rdata > out/run.sim.s.6.rho.-0.8.out  &
Rscript simulate_and_test.R nonmonotone_nonexchangeable -0.7 truncation "c()" sim/prms.sim.6.Rdata > out/run.sim.s.6.rho.-0.7.out  &
Rscript simulate_and_test.R nonmonotone_nonexchangeable -0.6 truncation "c()" sim/prms.sim.6.Rdata > out/run.sim.s.6.rho.-0.6.out  &
Rscript simulate_and_test.R nonmonotone_nonexchangeable -0.5 truncation "c()" sim/prms.sim.6.Rdata > out/run.sim.s.6.rho.-0.5.out  &
Rscript simulate_and_test.R nonmonotone_nonexchangeable -0.4 truncation "c()" sim/prms.sim.6.Rdata > out/run.sim.s.6.rho.-0.4.out  &
Rscript simulate_and_test.R nonmonotone_nonexchangeable -0.3 truncation "c()" sim/prms.sim.6.Rdata > out/run.sim.s.6.rho.-0.3.out  &
Rscript simulate_and_test.R nonmonotone_nonexchangeable -0.2 truncation "c()" sim/prms.sim.6.Rdata > out/run.sim.s.6.rho.-0.2.out  &
Rscript simulate_and_test.R nonmonotone_nonexchangeable -0.1 truncation "c()" sim/prms.sim.6.Rdata > out/run.sim.s.6.rho.-0.1.out  &
Rscript simulate_and_test.R nonmonotone_nonexchangeable 0 truncation "c()" sim/prms.sim.6.Rdata > out/run.sim.s.6.rho.0.out  &
Rscript simulate_and_test.R nonmonotone_nonexchangeable 0.1 truncation "c()" sim/prms.sim.6.Rdata > out/run.sim.s.6.rho.0.1.out  &
Rscript simulate_and_test.R nonmonotone_nonexchangeable 0.2 truncation "c()" sim/prms.sim.6.Rdata > out/run.sim.s.6.rho.0.2.out  &
Rscript simulate_and_test.R nonmonotone_nonexchangeable 0.3 truncation "c()" sim/prms.sim.6.Rdata > out/run.sim.s.6.rho.0.3.out  &
Rscript simulate_and_test.R nonmonotone_nonexchangeable 0.4 truncation "c()" sim/prms.sim.6.Rdata > out/run.sim.s.6.rho.0.4.out  &
Rscript simulate_and_test.R nonmonotone_nonexchangeable 0.5 truncation "c()" sim/prms.sim.6.Rdata > out/run.sim.s.6.rho.0.5.out  &
Rscript simulate_and_test.R nonmonotone_nonexchangeable 0.6 truncation "c()" sim/prms.sim.6.Rdata > out/run.sim.s.6.rho.0.6.out  &
Rscript simulate_and_test.R nonmonotone_nonexchangeable 0.7 truncation "c()" sim/prms.sim.6.Rdata > out/run.sim.s.6.rho.0.7.out  &
Rscript simulate_and_test.R nonmonotone_nonexchangeable 0.8 truncation "c()" sim/prms.sim.6.Rdata > out/run.sim.s.6.rho.0.8.out  &
Rscript simulate_and_test.R nonmonotone_nonexchangeable 0.9 truncation "c()" sim/prms.sim.6.Rdata > out/run.sim.s.6.rho.0.9.out  &
Rscript simulate_and_test.R CLmix 0.5 truncation "c()" sim/prms.sim.7.Rdata > out/run.sim.s.7.rho.0.5.out  &
Rscript simulate_and_test.R LogNormal 0 sum "c()" sim/prms.sim.8.Rdata > out/run.sim.s.8.rho.0.out  &
Rscript simulate_and_test.R Gaussian -0.9 gaussian "c()" sim/prms.sim.9.Rdata > out/run.sim.s.9.rho.-0.9.out  &
Rscript simulate_and_test.R Gaussian -0.8 gaussian "c()" sim/prms.sim.9.Rdata > out/run.sim.s.9.rho.-0.8.out  &
Rscript simulate_and_test.R Gaussian -0.7 gaussian "c()" sim/prms.sim.9.Rdata > out/run.sim.s.9.rho.-0.7.out  &
Rscript simulate_and_test.R Gaussian -0.6 gaussian "c()" sim/prms.sim.9.Rdata > out/run.sim.s.9.rho.-0.6.out  &
Rscript simulate_and_test.R Gaussian -0.5 gaussian "c()" sim/prms.sim.9.Rdata > out/run.sim.s.9.rho.-0.5.out  &
Rscript simulate_and_test.R Gaussian -0.4 gaussian "c()" sim/prms.sim.9.Rdata > out/run.sim.s.9.rho.-0.4.out  &
Rscript simulate_and_test.R Gaussian -0.3 gaussian "c()" sim/prms.sim.9.Rdata > out/run.sim.s.9.rho.-0.3.out  &
Rscript simulate_and_test.R Gaussian -0.2 gaussian "c()" sim/prms.sim.9.Rdata > out/run.sim.s.9.rho.-0.2.out  &
Rscript simulate_and_test.R Gaussian -0.1 gaussian "c()" sim/prms.sim.9.Rdata > out/run.sim.s.9.rho.-0.1.out  &
Rscript simulate_and_test.R Gaussian 0 gaussian "c()" sim/prms.sim.9.Rdata > out/run.sim.s.9.rho.0.out  &
Rscript simulate_and_test.R Gaussian 0.1 gaussian "c()" sim/prms.sim.9.Rdata > out/run.sim.s.9.rho.0.1.out  &
Rscript simulate_and_test.R Gaussian 0.2 gaussian "c()" sim/prms.sim.9.Rdata > out/run.sim.s.9.rho.0.2.out  &
Rscript simulate_and_test.R Gaussian 0.3 gaussian "c()" sim/prms.sim.9.Rdata > out/run.sim.s.9.rho.0.3.out  &
Rscript simulate_and_test.R Gaussian 0.4 gaussian "c()" sim/prms.sim.9.Rdata > out/run.sim.s.9.rho.0.4.out  &
Rscript simulate_and_test.R Gaussian 0.5 gaussian "c()" sim/prms.sim.9.Rdata > out/run.sim.s.9.rho.0.5.out  &
Rscript simulate_and_test.R Gaussian 0.6 gaussian "c()" sim/prms.sim.9.Rdata > out/run.sim.s.9.rho.0.6.out  &
Rscript simulate_and_test.R Gaussian 0.7 gaussian "c()" sim/prms.sim.9.Rdata > out/run.sim.s.9.rho.0.7.out  &
Rscript simulate_and_test.R Gaussian 0.8 gaussian "c()" sim/prms.sim.9.Rdata > out/run.sim.s.9.rho.0.8.out  &
Rscript simulate_and_test.R Gaussian 0.9 gaussian "c()" sim/prms.sim.9.Rdata > out/run.sim.s.9.rho.0.9.out  &
